global:
  imageTag: latest
  clusterName: kind-kind

accounts:
  enabled: true
  image:
    tag: latest
  replicaCount: 1

auth:
  enabled: true  
  image:
    tag: latest
  replicaCount: 1

blocker:
  enabled: true  
  image:
    tag: latest
  replicaCount: 1

cash:
  enabled: true  
  image:
    tag: latest
  replicaCount: 1

front:
  enabled: true
  image:
    tag: latest
  replicaCount: 1

exchange:
  enabled: true
  image:
    tag: latest
  replicaCount: 1

exgen:
  enabled: true
  image:
    tag: latest
  replicaCount: 1

notify:
  enabled: true  
  image:
    tag: latest
  replicaCount: 1

transfer:
  enabled: true  
  image:
    tag: latest
  replicaCount: 1
