version: '3.8'

services:
  config:
    build: ./config
    ports: ["8888:8888"]
    environment:
      - EUREKA_URL=http://eureka:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 100
      start_period: 20s




  eureka:
    build: ./eureka
    ports: ["8761:8761"]
    environment:
      - CONFIG_URL=http://config:8888 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 15s 
    depends_on:
      config:
        condition: service_healthy




  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_URL=http://eureka:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 100
      start_period: 20s
    command: >
      sh -c "
        echo 'Waiting for Config service registration...'
        until curl -f http://eureka:8761/eureka/apps/CONFIG 2>/dev/null | grep -q '8888'; do
          echo 'Config not yet registered, waiting...'
          sleep 5
        done
        sleep 30  
        echo 'Config registered, starting Gateway...'
        java -jar /app/app.jar
      "
#    restart: on-failure:3
    depends_on:
      eureka:
        condition: service_healthy




  auth:
    build: ./auth
    ports:
      - "9000:9000"
    environment:
      - EUREKA_URL=http://eureka:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/actuator/health"]
    depends_on:
      gateway:
        condition: service_healthy





  accounts:
    build: ./accounts
    ports:
      - "8082:8082"
    environment:
      - EUREKA_URL=http://eureka:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
    depends_on:
      auth:
        condition: service_healthy




  blocker:
    build: ./blocker
    ports:
      - "8087:8087"
    environment:
      - EUREKA_URL=http://eureka:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8087/actuator/health"]
    depends_on:
      auth:
        condition: service_healthy




  cash:
    build: ./cash
    ports:
      - "8085:8085"
    environment:
      - EUREKA_URL=http://eureka:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/actuator/health"]
    depends_on:
      auth:
        condition: service_healthy




  exchange:
    build: ./exchange
    ports:
      - "8083:8083"
    environment:
      - EUREKA_URL=http://eureka:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
    depends_on:
      auth:
        condition: service_healthy




  exgen:
    build: ./exgen
    ports:
      - "8084:8084"
    environment:
      - EUREKA_URL=http://eureka:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"]
    depends_on:
      auth:
        condition: service_healthy



  front:
    build: ./front
    ports:
      - "8081:8081"
    environment:
      - EUREKA_URL=http://eureka:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
    depends_on:
      auth:
        condition: service_healthy




  notify:
    build: ./notify
    ports:
      - "8088:8088"
    environment:
      - EUREKA_URL=http://eureka:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/actuator/health"]
    depends_on:
      auth:
        condition: service_healthy




  transfer:
    build: ./transfer
    ports:
      - "8086:8086"
    environment:
      - EUREKA_URL=http://eureka:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/actuator/health"]
    depends_on:
      auth:
        condition: service_healthy










