apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-headless
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      # different nodes
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: kafka
            topologyKey: kubernetes.io/hostname
      containers:
      - name: kafka
        image: {{ .Values.image }}
        ports:
        - containerPort: 9092
        - containerPort: 9093
        env:
        - name: KAFKA_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_NODE_ID
          value: "0"
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "0@kafka-0.kafka-headless:9093,1@kafka-1.kafka-headless:9093"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://:9092,CONTROLLER://:9093"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://${HOSTNAME}.kafka:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
        - name: KAFKA_NUM_PARTITIONS
          value: "2"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "2"
        command:
        - "sh"
        - "-c"
        - |
          # node.id from pod name
          export KAFKA_NODE_ID=$(echo $HOSTNAME | sed 's/kafka-//')
          echo "Starting Kafka with node.id: $KAFKA_NODE_ID"
          printenv
          ls -al /kafka/data
          cat /opt/kafka/config/server.properties
          # start kafka with settings from env var
          /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties
        volumeMounts:
        - name: data
          mountPath: /kafka/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.storageSize }}