#FROM openjdk:21-jdk-slim
FROM eclipse-temurin:21-jdk-alpine

RUN apt-get update && \
    apt-get install -y curl netcat-openbsd && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY target/*.jar app.jar

EXPOSE 9000


ENTRYPOINT ["java", "-jar", "app.jar"]