# Docker image
image:
  repository: exgen
  tag: latest
  pullPolicy: IfNotPresent

# Service
service:
  type: ClusterIP
  port: 8080

# Configuration
config:
  serverPort: 8080
  logging:
    level: "DEBUG"

oauth2:
  client:
    id: "exgen"           
    secret: "exgenPassword"

# Deployment
replicaCount: 1