{
 "title": "business metrics",
 "description": "business metrics for bank application",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": " successful and failed logins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "bank_login_success_total", "legendFormat": "__auto" },
    { "expr": "bank_login_fail_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "successfull, failed and blocked transfers",
   "type": "timeseries",
   "description": "failed transfers include blocked",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "bank_transfer_success_total", "legendFormat": "__auto" },
    { "expr": "bank_transfer_fail_total", "legendFormat": "__auto" },
    { "expr": "bank_transfer_blocked_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "exchange rate updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "bank_exchange_rates_update_seconds_max",
     "legendFormat": "__auto"
    },
    {
     "expr": "bank_exchange_rate_last_update_time - bank_exchange_rate_last_update_time offset 15s\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "delta(bank_exchange_rate_last_update_time[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}